#define STB_IMAGE_IMPLEMENTATION
#include "../../../third_party/stb_image.h"
#include "mesh.hpp"
#include <assimp/Importer.hpp>
#include <assimp/scene.h>
#include <assimp/postprocess.h>
#include <filesystem>
#include <fstream>
#include <iostream>
#include <functional>
#include <unordered_map>
#include <cmath>
namespace cry {
static unsigned imageTexture(const std::string&p,bool srgb=false){int w=0,h=0,n=0;stbi_uc*d=stbi_load(p.c_str(),&w,&h,&n,4);if(!d)return 0;unsigned t=0;gl::GenTextures(1,&t);gl::BindTexture(GL_TEXTURE_2D,t);gl::TexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MIN_FILTER,GL_LINEAR_MIPMAP_LINEAR);gl::TexParameteri(GL_TEXTURE_2D,GL_TEXTURE_MAG_FILTER,GL_LINEAR);gl::TexParameteri(GL_TEXTURE_2D,GL_TEXTURE_WRAP_S,GL_REPEAT);gl::TexParameteri(GL_TEXTURE_2D,GL_TEXTURE_WRAP_T,GL_REPEAT);gl::TexImage2D(GL_TEXTURE_2D,0,srgb?0x8C40:GL_RGBA,w,h,0,GL_RGBA,GL_UNSIGNED_BYTE,d);gl::GenerateMipmap(GL_TEXTURE_2D);stbi_image_free(d);return t;}
static std::string texPath(const aiMaterial*m,aiTextureType type,const std::filesystem::path&base){aiString s;if(m->GetTexture(type,0,&s)!=AI_SUCCESS)return{};std::string x=s.C_Str();if(!x.empty()&&x[0]=='*')return{};return(base/x).lexically_normal().string();}
static MeshPart makePart(const aiMesh*m,const aiMaterial*mat,const std::filesystem::path&base){
 std::vector<float>d;d.reserve(m->mNumFaces*3*11);
 for(unsigned i=0;i<m->mNumFaces;i++){const auto&face=m->mFaces[i];if(face.mNumIndices<3)continue;for(unsigned k=1;k+1<face.mNumIndices;k++){unsigned ids[3]={face.mIndices[0],face.mIndices[k],face.mIndices[k+1]};for(unsigned q:ids){auto p=m->mVertices[q];auto n=m->HasNormals()?m->mNormals[q]:aiVector3D(0,1,0);auto uv=m->HasTextureCoords(0)?m->mTextureCoords[0][q]:aiVector3D(0,0,0);auto t=m->HasTangentsAndBitangents()?m->mTangents[q]:aiVector3D(1,0,0);d.insert(d.end(),{p.x,p.y,p.z,n.x,n.y,n.z,uv.x,1.f-uv.y,t.x,t.y,t.z});}}}
 MeshPart r{};if(d.empty())return r;gl::GenVertexArrays(1,&r.vao);gl::BindVertexArray(r.vao);gl::GenBuffers(1,&r.vbo);gl::BindBuffer(GL_ARRAY_BUFFER,r.vbo);gl::BufferData(GL_ARRAY_BUFFER,(std::ptrdiff_t)(d.size()*sizeof(float)),d.data(),GL_STATIC_DRAW);int stride=11*sizeof(float);gl::VertexAttribPointer(0,3,GL_FLOAT,GL_FALSE,stride,(void*)0);gl::EnableVertexAttribArray(0);gl::VertexAttribPointer(1,3,GL_FLOAT,GL_FALSE,stride,(void*)(3*sizeof(float)));gl::EnableVertexAttribArray(1);gl::VertexAttribPointer(2,2,GL_FLOAT,GL_FALSE,stride,(void*)(6*sizeof(float)));gl::EnableVertexAttribArray(2);gl::VertexAttribPointer(3,3,GL_FLOAT,GL_FALSE,stride,(void*)(8*sizeof(float)));gl::EnableVertexAttribArray(3);r.count=(int)d.size()/11;
 auto alb=texPath(mat,aiTextureType_BASE_COLOR,base);if(alb.empty())alb=texPath(mat,aiTextureType_DIFFUSE,base);auto nor=texPath(mat,aiTextureType_NORMALS,base);if(nor.empty())nor=texPath(mat,aiTextureType_NORMAL_CAMERA,base);auto rough=texPath(mat,aiTextureType_DIFFUSE_ROUGHNESS,base);
 if(!alb.empty())r.albedo=imageTexture(alb,true);if(!nor.empty())r.normal=imageTexture(nor,false);if(!rough.empty())r.roughness=imageTexture(rough,false);
 aiColor4D c(1,1,1,1);mat->Get(AI_MATKEY_BASE_COLOR,c);r.transparent=c.a<.98f;return r;
}
Mesh loadModel(const std::string&path){Assimp::Importer imp;const aiScene*s=imp.ReadFile(path,aiProcess_Triangulate|aiProcess_GenSmoothNormals|aiProcess_CalcTangentSpace|aiProcess_JoinIdenticalVertices|aiProcess_ImproveCacheLocality|aiProcess_ValidateDataStructure);if(!s||!s->mRootNode){std::cerr<<"Assimp: "<<imp.GetErrorString()<<"\n";return{};}Mesh out;auto base=std::filesystem::path(path).parent_path();std::function<void(aiNode*)>walk=[&](aiNode*n){for(unsigned i=0;i<n->mNumMeshes;i++){auto m=s->mMeshes[n->mMeshes[i]];out.parts.push_back(makePart(m,s->mMaterials[m->mMaterialIndex],base));}for(unsigned i=0;i<n->mNumChildren;i++)walk(n->mChildren[i]);};walk(s->mRootNode);return out;}
Mesh loadObj(const std::string&path){return loadModel(path);}
void Mesh::draw()const{for(const auto&p:parts){if(!p.vao||!p.count)continue;if(p.albedo){gl::ActiveTexture(GL_TEXTURE0);gl::BindTexture(GL_TEXTURE_2D,p.albedo);}if(p.normal){gl::ActiveTexture(GL_TEXTURE0+1);gl::BindTexture(GL_TEXTURE_2D,p.normal);}if(p.roughness){gl::ActiveTexture(GL_TEXTURE0+2);gl::BindTexture(GL_TEXTURE_2D,p.roughness);}gl::BindVertexArray(p.vao);glDrawArrays(GL_TRIANGLES,0,p.count);}}
static void v(std::vector<float>&d,Vec3 p,Vec3 n,float u,float w){d.insert(d.end(),{p.x,p.y,p.z,n.x,n.y,n.z,u,w,1,0,0});}
static void tri(std::vector<float>&d,Vec3 a,Vec3 b,Vec3 c){Vec3 n=(b-a).cross(c-a).normalized();v(d,a,n,0,0);v(d,b,n,1,0);v(d,c,n,1,1);}
static Mesh from(const std::vector<float>&d){Mesh m;if(d.empty())return m;MeshPart p{};gl::GenVertexArrays(1,&p.vao);gl::BindVertexArray(p.vao);gl::GenBuffers(1,&p.vbo);gl::BindBuffer(GL_ARRAY_BUFFER,p.vbo);gl::BufferData(GL_ARRAY_BUFFER,(std::ptrdiff_t)(d.size()*sizeof(float)),d.data(),GL_STATIC_DRAW);int s=11*sizeof(float);gl::VertexAttribPointer(0,3,GL_FLOAT,GL_FALSE,s,(void*)0);gl::EnableVertexAttribArray(0);gl::VertexAttribPointer(1,3,GL_FLOAT,GL_FALSE,s,(void*)(3*sizeof(float)));gl::EnableVertexAttribArray(1);gl::VertexAttribPointer(2,2,GL_FLOAT,GL_FALSE,s,(void*)(6*sizeof(float)));gl::EnableVertexAttribArray(2);gl::VertexAttribPointer(3,3,GL_FLOAT,GL_FALSE,s,(void*)(8*sizeof(float)));gl::EnableVertexAttribArray(3);p.count=d.size()/11;m.parts.push_back(p);return m;}
static void side(std::vector<float>&v,float y0,float y1,float r0,float r1,int n){for(int i=0;i<n;i++){float a=6.2831853f*i/n,b=6.2831853f*(i+1)/n;Vec3 p0{std::cos(a)*r0,y0,std::sin(a)*r0},p1{std::cos(b)*r0,y0,std::sin(b)*r0},q0{std::cos(a)*r1,y1,std::sin(a)*r1},q1{std::cos(b)*r1,y1,std::sin(b)*r1};tri(v,p0,p1,q1);tri(v,p0,q1,q0);}}
Mesh makePine(){std::vector<float>d;side(d,0,2.5f,.2f,.12f,12);side(d,.9f,3.15f,1.25f,.06f,14);side(d,1.75f,4.15f,.96f,.05f,14);side(d,2.65f,5.35f,.68f,.02f,14);return from(d);}
Mesh makeRock(){std::vector<float>d;for(int r=0;r<3;r++)for(int i=0;i<12;i++){float y0=-.45f+r*.4f,y1=y0+.4f,r0=1-r*.2f,r1=1-(r+1)*.2f,a=6.2831853f*i/12,b=6.2831853f*(i+1)/12;Vec3 p0{std::cos(a)*r0,y0,std::sin(a)*r0},p1{std::cos(b)*r0,y0,std::sin(b)*r0},q0{std::cos(a)*r1,y1,std::sin(a)*r1},q1{std::cos(b)*r1,y1,std::sin(b)*r1};tri(d,p0,p1,q1);tri(d,p0,q1,q0);}return from(d);}
Mesh makeGround(int n,float size){std::vector<float>d;for(int z=0;z<n;z++)for(int x=0;x<n;x++){float x0=-size/2+size*x/n,x1=-size/2+size*(x+1)/n,z0=-size/2+size*z/n,z1=-size/2+size*(z+1)/n;Vec3 a{x0,0,z0},b{x1,0,z0},c{x1,0,z1},e{x0,0,z1};v(d,a,{0,1,0},x/4.f,z/4.f);v(d,c,{0,1,0},(x+1)/4.f,(z+1)/4.f);v(d,b,{0,1,0},(x+1)/4.f,z/4.f);v(d,a,{0,1,0},x/4.f,z/4.f);v(d,e,{0,1,0},x/4.f,(z+1)/4.f);v(d,c,{0,1,0},(x+1)/4.f,(z+1)/4.f);}return from(d);}
Mesh makeCube(){std::vector<float>d;Vec3 p[8]={{-.5f,-.5f,-.5f},{.5f,-.5f,-.5f},{.5f,.5f,-.5f},{-.5f,.5f,-.5f},{-.5f,-.5f,.5f},{.5f,-.5f,.5f},{.5f,.5f,.5f},{-.5f,.5f,.5f}};int f[6][4]={{0,1,2,3},{5,4,7,6},{4,0,3,7},{1,5,6,2},{3,2,6,7},{4,5,1,0}};for(auto&q:f){tri(d,p[q[0]],p[q[1]],p[q[2]]);tri(d,p[q[0]],p[q[2]],p[q[3]]);}return from(d);}
}